@api = http://localhost:3000/api/interno

### get internos
GET {{api}}

### create interno
POST {{api}}
Content-Type: application/json

{
    
    "name": "12",
    "userId": "isaiassalas2",
    "lineaId": "1"
}

### update interno
PUT {{api}}/5
Content-Type: application/json

{
    "id":"",
    "name": "isaias",
    "userId": "isaiassalas4",
    "lineaId": "3"
}

### delete interno
DELETE {{api}}/15

### get interno
GET {{api}}/14



