@api = http://localhost:3000/api/linea

### get lineas
GET {{api}}

### get lineas interno
GET {{api}}/user/1

### get lineas interno 
GET {{api}}/interno/1

### create linea
POST {{api}}
Content-Type: application/json

{
    "id":2,
    "name": "isaias",
    "lastname": "salas",
    "phone": "70881108",
    "email": "salas@gmial.com",
    "password": "salas",
    "roleId": 1
}

### update linea
PUT {{api}}/scr-67
Content-Type: application/json

{
    "id":"scr-67",
    "name": "linea 68",
    "description": "blabla",
    "phone": "70881108",
    "directionLat": "-17.871478",
    "directionLon": "-63.141013",
    "colorPr": "F29100",
    "colorBg": "EBEBEB"
}

### delete linea
DELETE {{api}}/15

### get linea
GET {{api}}/2



