@api = http://localhost:3000/api/user

### get users
GET {{api}}

### create user
POST {{api}}
Content-Type: application/json

{
    "id":"ola",
    "name": "isaias",
    "lastname": "salas",
    "phone": "70881108",
    "email": "salas@gmial.com",
    "password": "salas",
    "roleId": 0

    
}
### create user
POST {{api}}
Content-Type: application/json

{
    "id":"r",
    "name":"f",
    "lastname":"f",
    "phone":"g",
    "email":"v",
    "password":null,
    "createdAt":null,
    "updatedAt":null,
    "roleId":0
    }

### update user
PUT {{api}}/16
Content-Type: application/json

{
    "name": "isaias",
    "lastname": "salas",
    "phone": "70881108",
    "email": "salas@gmial.com"
}

### delete user
DELETE {{api}}/0

### get user
GET {{api}}/14



