@user = http://localhost:3000/api/user
@linea = http://localhost:3000/api/linea
@interno = http://localhost:3000/api/interno

//////////////////////////////////////////////////////////////////////
### create linea
POST {{linea}}
Content-Type: application/json

{
    "name": "linea 58",
    "direction":{"lat":-17.871478, "lng":-63.141013},
    "color": {"top": "F29100", "bottom": "EBEBEB"},
    "phone": "70881108",
    "ida":{
        "origin": {
            "location":{"lat": -17.792102, "lng": -63.178993}, 
            "time":0},
        "destination": {
            "location":{"lat": -17.774608, "lng": -63.182515}, 
            "time":5},
        "waypoint": []
    },
    "vuelta":{
        "origin": {
            "location":{"lat": -17.792102, "lng": -63.178993}, 
            "time":0},
        "destination": {
            "location":{"lat": -17.774608, "lng": -63.182515}, 
            "time":5},
        "waypoint": []
    }
}

### create linea 
POST {{linea}}
Content-Type: application/json

{
    "name": "linea 67",
    "direction":{"lat":-17.871478, "lng":-63.141013 },
    "color": {"top": "F29100", "bottom": "EBEBEB"},
    "phone": "70881108",
    "ida":{
        "origin": {
            "location":{"lat": -17.792102, "lng": -63.178993}, 
            "time":0},
        "destination": {
            "location":{"lat": -17.774608, "lng": -63.182515}, 
            "time":5},
        "waypoint": []
    },
    "vuelta":{
        "origin": {
            "location":{"lat": -17.792102, "lng": -63.178993}, 
            "time":0},
        "destination": {
            "location":{"lat": -17.774608, "lng": -63.182515}, 
            "time":5},
        "waypoint": []
    }
}

### create linea 
POST {{linea}}
Content-Type: application/json

{
    "name": "linea 30",
    "direction":{"lat":-17.871478, "lng":-63.141013},
    "color": {"top": "F29100", "bottom": "EBEBEB"},
    "phone": "70881108",
    "ida":{
        "origin": {
            "location":{"lat": -17.792102, "lng": -63.178993}, 
            "time":0},
        "destination": {
            "location":{"lat": -17.774608, "lng": -63.182515}, 
            "time":5},
        "waypoint": []
    },
    "vuelta":{
        "origin": {
            "location":{"lat": -17.792102, "lng": -63.178993}, 
            "time":0},
        "destination": {
            "location":{"lat": -17.774608, "lng": -63.182515}, 
            "time":5},
        "waypoint": []
    }
}

### create linea 
POST {{linea}}
Content-Type: application/json

{
    "name": "linea 121",
    "direction":{"lat":-17.871478, "lng":-63.141013},
    "color": {"top": "F29100", "bottom": "EBEBEB"},
    "phone": "70881108",
    "ida":{
        "origin": {
            "location":{"lat": -17.792102, "lng": -63.178993}, 
            "time":0},
        "destination": {
            "location":{"lat": -17.774608, "lng": -63.182515}, 
            "time":5},
        "waypoint": []
    },
    "vuelta":{
        "origin": {
            "location":{"lat": -17.792102, "lng": -63.178993}, 
            "time":0},
        "destination": {
            "location":{"lat": -17.774608, "lng": -63.182515}, 
            "time":5},
        "waypoint": []
    }
}

//////////////////////////////////////////////////////////////////////

### create user
POST {{user}}
Content-Type: application/json

{
    "id":"admin",
    "name": "adminN",
    "lastname": "adminLN",
    "phone": "70881108",
    "email": "admin@gmial.com",
    "password": "admin",
    "admin": true
}

### create user
POST {{user}}
Content-Type: application/json

{
    "id":"control",
    "name": "controlN",
    "lastname": "controlLN",
    "phone": "70881108",
    "email": "control@gmial.com",
    "password": "control",
    "admin": false,
    "lineaId": 1
}

### create user
POST {{user}}
Content-Type: application/json

{
    "id":"control1",
    "name": "contro1lN",
    "lastname": "control1LN",
    "phone": "70881108",
    "email": "control1@gmial.com",
    "password": "control",
    "admin": false
}

### create user
POST {{user}}
Content-Type: application/json

{
    "id":"socio",
    "name": "socioN",
    "lastname": "socioLN",
    "phone": "70881108",
    "email": "socio@gmial.com",
    "password": "socio",
    "admin": false
}

### create user
POST {{user}}
Content-Type: application/json

{
    "id":"socio1",
    "name": "socioL",
    "lastname": "socioLN",
    "phone": "70881108",
    "email": "socio@gmial.com",
    "password": "socio",
    "admin": false
}

//////////////////////////////////////////////////////////////////////

### create interno
POST {{interno}}
Content-Type: application/json

{
    "name": "12",
    "userId": "socio",
    "lineaId": 1
}

### create interno
POST {{interno}}
Content-Type: application/json

{
    "name": "30",
    "userId": "socio1",
    "lineaId": 2
}

### create interno
POST {{interno}}
Content-Type: application/json

{
    "name": "20",
    "userId": "socio1",
    "lineaId": 3
}